package com.incubasys.formblok.common.data.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
import org.joda.time.DateTime

/**
 * Formblok Mobile
 * API documentation for the mobile endpoints of formblok.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *
 * @param id
 * @param url
 * @param userId
 * @param createdAt
 */
@Parcelize
data class Document(
    val id: kotlin.Int = -1,
    val url: kotlin.String = "",
    val userId: kotlin.Int = -1,
    val createdAt: DateTime? = null

) : Parcelable {
}