package com.incubasys.formblok.common.data.model

import com.google.gson.annotations.SerializedName

/**
 * Formblok Mobile
 * API documentation for the mobile endpoints of formblok.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *
 * @param email
 */
data class Email(
    @SerializedName("email") val email: kotlin.String? = ""
)