package com.incubasys.formblok.common.data.model

import com.google.gson.annotations.SerializedName

/**
 * Formblok Mobile
 * API documentation for the mobile endpoints of formblok.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *
 * @param email
 * @param password
 */
class LoginInput(
    @SerializedName("email") var email: kotlin.String? = null,
    @SerializedName("password")
    var password: kotlin.String? = null

)