package com.incubasys.formblok.common.data.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * Formblok Mobile
 * API documentation for the mobile endpoints of formblok.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *
 * @param message
 */
@Parcelize
data class Message(
    var message: String = "",
    var code: Int = -1
) : Parcelable {

}
