/**
 * Formblok Mobile
 * API documentation for the mobile endpoints of formblok.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.incubasys.formblok.common.data.model


/**
 *
 * @param name
 * @param length
 * @param width
 */
data class RoomInput(
    val name: String,
    val length: String,
    val width: String
)