package com.incubasys.formblok.common.data.model

/**
* Formblok Mobile
* API documentation for the mobile endpoints of formblok.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


/**
 * 
 * @param sid 
 * @param stoken 
 * @param user 
 */
data class SessionOutput (
    val sid: Int,
    val stoken: String
,
    val user: User? = null
) {
}