/**
* Formblok Mobile
* API documentation for the mobile endpoints of formblok.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.incubasys.formblok.projects.data.model



/**
 * 
 * @param id 
 * @param name 
 * @param properties 
 */
data class ProjectOutput (
    val id: Int,
    val name: String
,
    val properties: MutableList<PropertyOutput>? = null
) {
}