/**
 * Formblok Mobile
 * API documentation for the mobile endpoints of formblok.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.incubasys.formblok.projects.data.model

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.android.parcel.Parcelize


/**
 *
 * @param id
 * @param name
 * @param properties
 */
@Parcelize
data class Project(
    @SerializedName("id") var id: Int = -1,
    @SerializedName("name") var name: String = "",
    @SerializedName("project_type") var type: Int = -1,
    @SerializedName("properties") var properties: MutableList<PropertyMinimal>? = mutableListOf(),
    @SerializedName("share_url") var shareUrl: String = "",
    @Transient var isSelectableProject: Boolean = false
) : Parcelable {
}