/**
* Formblok Mobile
* API documentation for the mobile endpoints of formblok.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.incubasys.formblok.projects.data.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize


/**
 * 
 * @param id 
 * @param roomId 
 * @param length 
 * @param width 
 * @param area 
 */
@Parcelize
data class PropertyRoomOutput (
    var id: Int = -1,
    var roomId:Int = -1,
    var name :String = "",
    var length: Double = 0.0,
    var width: Double = 0.0,
    var area: Double = 0.0

) : Parcelable {
}