/**
* Formblok Mobile
* API documentation for the mobile endpoints of formblok.
*
* OpenAPI spec version: v1
*
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.incubasys.formblok.projects.data.model

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.android.parcel.Parcelize


/**
 *
 * @param id
 * @param name
 */
@Parcelize
data class PropertyMinimal (
    @SerializedName("id") var id: Int = -1,
    @SerializedName("street_address") var address: String? = "",
    @SerializedName("area") var area: String=""
) : Parcelable